### ISSUE TITLE
tu presentación?

### ISSUE THREAD

**Issue by rod00001** [mayds28/clase1#1]

**Comment by mayds28** [comment]
Listo profe, disculpe no la había subido.

**Comment by mayds28** [comment]
[Programación orientada a objetos MDSL 6TV65 2.pptx](https://github.com/mayds28/clase1/files/14706039/Programacion.orientada.a.objetos.MDSL.6TV65.2.pptx)

**Comment by rod00001** [comment]
es en el repositorio.
________________________________
De: mayds28 ***@***.***>
Enviado: jueves, 21 de marzo de 2024 1:25 p. m.
Para: mayds28/clase1 ***@***.***>
Cc: Rodolfo Villalobos Martinez ***@***.***>; Author ***@***.***>
Asunto: [ADVERTENCIA, MENSAJE EXTERNO] Re: [mayds28/clase1] tu presentación? (Issue #1)



ADVERTENCIA, REMITENTE EXTERNO
ESTE MENSAJE SE ORIGINÓ FUERA DE LOS SERVICIOS INSTITUCIONALES. NO HAGA CLIC EN ENLACES NI ABRA ARCHIVOS ADJUNTOS Y LO MAS IMPORTANTE NO PROPORCIONE INFORMACIÓN A MENOS QUE RECONOZCA AL REMITENTE Y TENGA CERTEZA QUE EL CONTENIDO ES SEGURO.


Programación orientada a objetos MDSL 6TV65 2.pptx<https://github.com/mayds28/clase1/files/14706039/Programacion.orientada.a.objetos.MDSL.6TV65.2.pptx>
